\documentclass{beamer}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{1, 0.894, 0.769}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.824,0.412,0.118}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{1,0.894,0.71}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.824,0.706,0.549}{#1}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{1,0.894,0.769}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{1,0.894,0.769}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.941,0.902,0.549}{#1}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.804,0.776,0.451}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.78,0.941,0.545}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{1,0.78,0.769}{#1}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{../371g-slides}
\title{Interactions 1}
\subtitle{Lecture 10}
\author{STA 371G}

% This is adapted from http://community.amstat.org/stats101/resources/viewdocument?DocumentKey=e4f8d3f1-41a3-4f01-9f8b-f8fbe1562c15&tab=librarydocuments&CommunityKey=5ad27b39-58d0-49e9-9f6f-0c39c82a0401.
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
  
  

  \frame{\maketitle}

  % Show outline at beginning of each section
  \AtBeginSection[]{ 
    \begin{frame}<beamer>
      \tableofcontents[currentsection]
    \end{frame}
  }

  %%%%%%% Slides start here %%%%%%%

  \begin{darkframes}
    \begin{frame}{Housing price data}
      Let's return to the 2007 housing price data set from Saratoga County, NY that you looked at for HW2.
      \begin{itemize}
        \item \textbf{Price}: price of house (\$)
        \item \textbf{Living.Area}: amount of living space (sq ft)
        \item \textbf{Fireplace}: whether house has a fireplace (yes/no)
      \end{itemize}
      \lc
    \end{frame}

    \begin{frame}[fragile]{How much is a fireplace worth?}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{boxplot}\hlstd{(Price} \hlopt{~} \hlstd{Fireplace,} \hlkwc{data}\hlstd{=houses,}
  \hlkwc{col}\hlstd{=}\hlstr{'gray'}\hlstd{,} \hlkwc{ylab}\hlstd{=}\hlstr{'Price'}\hlstd{)}
\end{alltt}
\end{kframe}
\input{/tmp/figures/unnamed-chunk-2-1.tikz}

\end{knitrout}
    \end{frame}

    \begin{frame}[fragile]{How much is a fireplace worth?}
      

      If we regress Price on Fireplace, we get the regression equation
      \[
        \widehat{\text{Price}} = 174653 + 65261\cdot(\text{Fireplace = Yes})
      \]
      The average difference between houses with and without a fireplace is \$65261.
      \lc
    \end{frame}

    \begin{frame}{What is the relationship between price and size?}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}
\input{/tmp/figures/unnamed-chunk-4-1.tikz}

\end{knitrout}
    \end{frame}

    \begin{frame}{Predicting price from living area}
      \begin{center}
        Let's start by creating a simple regression predicting \\
        price from living area (in sq ft).
      \end{center}
    \end{frame}

    \begin{frame}[fragile]
      \fontsize{8}{8}\selectfont
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{model1} \hlkwb{<-} \hlkwd{lm}\hlstd{(Price} \hlopt{~} \hlstd{Living.Area,} \hlkwc{data}\hlstd{=houses)}
\hlkwd{summary}\hlstd{(model1)}
\end{alltt}
\begin{verbatim}

Call:
lm(formula = Price ~ Living.Area, data = houses)

Residuals:
    Min      1Q  Median      3Q     Max 
-277022  -39371   -7726   28350  553325 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 13439.39    4992.35    2.69   0.0072 ** 
Living.Area   113.12       2.68   42.17   <2e-16 ***
---
Signif. codes:  0 '***' 0 '**' 0 '*' 0 '.' 0 ' ' 1

Residual standard error: 69100 on 1726 degrees of freedom
Multiple R-squared:  0.507,	Adjusted R-squared:  0.507 
F-statistic: 1.78e+03 on 1 and 1726 DF,  p-value: <2e-16
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}
      \begin{center}
        Can we do better by adding a dummy variable for fireplace to the model?
      \end{center}
    \end{frame}

    \begin{frame}[fragile]
      \fontsize{8}{8}\selectfont
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{model2} \hlkwb{<-} \hlkwd{lm}\hlstd{(Price} \hlopt{~} \hlstd{Living.Area} \hlopt{+} \hlstd{Fireplace,} \hlkwc{data}\hlstd{=houses)}
\hlkwd{summary}\hlstd{(model2)}
\end{alltt}
\begin{verbatim}

Call:
lm(formula = Price ~ Living.Area + Fireplace, data = houses)

Residuals:
    Min      1Q  Median      3Q     Max 
-271421  -39935   -7887   28215  554651 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept)  13599.16    4991.70    2.72   0.0065 ** 
Living.Area    111.22       2.97   37.48   <2e-16 ***
FireplaceYes  5567.38    3716.95    1.50   0.1344    
---
Signif. codes:  0 '***' 0 '**' 0 '*' 0 '.' 0 ' ' 1

Residual standard error: 69100 on 1725 degrees of freedom
Multiple R-squared:  0.508,	Adjusted R-squared:  0.508 
F-statistic:  891 on 2 and 1725 DF,  p-value: <2e-16
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}
      By adding the dummy variable, we are essentially fitting two regression lines:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}
\input{/tmp/figures/unnamed-chunk-7-1.tikz}

\end{knitrout}
    \end{frame}

    \begin{frame}{Interactions}
      \begin{center}
        Our regression equation is
        \[
          \widehat{\text{Price}} = 13599
            + 111 \cdot\text{Living.Area}
            + 5567 \cdot\text{FireplaceYes}.
        \]
        
        \bigskip\pause

        What if the \emph{slope} of the best-fit line is different for houses with a fireplace than for houses without?

        \bigskip\pause

        Equivalently, what if the \emph{effect} of having a bigger house is different for houses with fireplaces than for houses without fireplaces?
      \end{center}
    \end{frame}
    
    \begin{frame}{Interactions}
      To model this, we can add an \alert{interaction term} that consists of the product of the two predictors:
      \begin{multline*}
        \text{Price} = \beta_0 + \beta_1\cdot\text{Living.Area} + \beta_2\cdot\text{FireplaceYes}
        \\ + \beta_3\cdot\text{Living.Area}\cdot\text{FireplaceYes} + \epsilon_i.
      \end{multline*}

      \pause\bigskip

      Now, the \emph{slope} of Living.Area depends on the \emph{value} of Fireplace!
    \end{frame}

    \begin{frame}[fragile]
      \fontsize{8}{8}\selectfont
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{model3} \hlkwb{<-} \hlkwd{lm}\hlstd{(Price} \hlopt{~} \hlstd{Living.Area} \hlopt{*} \hlstd{Fireplace,} \hlkwc{data}\hlstd{=houses)}
\hlkwd{summary}\hlstd{(model3)}
\end{alltt}
\begin{verbatim}

Call:
lm(formula = Price ~ Living.Area * Fireplace, data = houses)

Residuals:
    Min      1Q  Median      3Q     Max 
-241710  -39588   -7821   28480  542055 

Coefficients:
                          Estimate Std. Error t value   Pr(>|t|)    
(Intercept)               40901.29    8234.66    4.97 0.00000075 ***
Living.Area                  92.36       5.41   17.07    < 2e-16 ***
FireplaceYes             -37610.41   11024.85   -3.41    0.00066 ***
Living.Area:FireplaceYes     26.85       6.46    4.16 0.00003376 ***
---
Signif. codes:  0 '***' 0 '**' 0 '*' 0 '.' 0 ' ' 1

Residual standard error: 68800 on 1724 degrees of freedom
Multiple R-squared:  0.513,	Adjusted R-squared:  0.512 
F-statistic:  605 on 3 and 1724 DF,  p-value: <2e-16
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}
      This corresponds to the regression equation:
      \begin{multline*}
        \widehat{\text{Price}} = 40901
          + 92 \cdot\text{Living.Area}
          - 37610 \cdot\text{FireplaceYes} \\
          + 27 \cdot\text{Living.Area}\cdot\text{FireplaceYes}
      \end{multline*}
      \pause
      In other words, for houses without a fireplace:
      \[
        \widehat{\text{Price}} = 40901
        + 92 \cdot\text{Living.Area}
      \]
      \pause
      And for houses with a fireplace:
      \[
        \widehat{\text{Price}} = (40901 - 37610)
        + (92 + 27) \cdot\text{Living.Area}
      \]
    \end{frame}

    \begin{frame}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}
\input{/tmp/figures/unnamed-chunk-9-1.tikz}

\end{knitrout}
      \lc
      \note{Do both LC questions about interpretations in either direction}
    \end{frame}

    \begin{frame}[fragile]{Main effects and interaction effects}
      \fontsize{9}{9}\selectfont

      In the output, the coeffficients for Living.Space and Fireplace are \alert{main effects}, and the coefficient for $\text{Living.Space}\cdot\text{Fireplace}$ is an \alert{interaction effect}.

      
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hlstd{(model3)}\hlopt{$}\hlstd{coefficients}
\end{alltt}
\begin{verbatim}
                         Estimate Std. Error t value Pr(>|t|)
(Intercept)                 40901     8234.7     5.0  7.5e-07
Living.Area                    92        5.4    17.1  1.8e-60
FireplaceYes               -37610    11024.9    -3.4  6.6e-04
Living.Area:FireplaceYes       27        6.5     4.2  3.4e-05
\end{verbatim}
\end{kframe}
\end{knitrout}

      \pause
      The main effect for Living.Area (92.36) represents the predicted incremental effect of each additional square foot of living space, when there is no fireplace present.

      \bigskip\pause
      When we have an interaction term in the model, we \emph{must} include the main effect as well!

      \lc
    \end{frame}

  \end{darkframes}

  \end{document}
